### login
post http://localhost:8000/auth/login
Content-Type: application/json

{
    "name":"zxk7516",
    "password":"111111"
}
### register
post http://localhost:8000/auth/register
Content-Type: application/json

{
    "name":"zxk",
    "username":"zxk7516",
    "email":"zxk7516@gmail.com",
    "password":"111111"
}